homeHTML=function(){
 const read=COURSE41.lessons.filter(l=>cpState41().read[l.id]).length;
 const done=regularTasks42().filter(t=>coursePassed41(t.id)).length;
 const guided=GUIDES43.filter(doneGuide43).length;
 return '<section class="hero"><span class="eyebrow">경제 개념 학습실</span><h1>경제 개념을 배우고<br>직접 풀어 보세요.</h1><p>15단원·72강에서 개념을 익히고 연습 문제에 적용해 보세요. 풀이가 막히면 단계별 연습에서 계산과 판단의 과정을 하나씩 확인할 수 있습니다.</p><div class="actions"><button class="gold" data-action="c41-resume">개념 학습 이어서</button><button data-action="g43-resume">단계별 풀이 이어서</button><button data-action="v42-labs">조건을 바꾸며 실험하기</button></div></section>'
 +'<div class="statgrid"><div class="stat"><b>'+read+'/72</b><span>읽은 강의</span></div><div class="stat"><b>'+done+'/195</b><span>정답을 맞힌 연습 문제</span></div><div class="stat"><b>'+guided+'/30</b><span>완료한 단계별 연습</span></div><div class="stat"><b>'+CAMPAIGNS42.length+'</b><span>종합 문제 묶음</span></div></div>'
 +'<h2 class="section">주제별로 공부하기</h2>'+districtMap42()
 +'<section class="card section"><h2>배운 내용 다지기</h2><div class="actions"><button data-action="nav" data-view="library">전체 강의 보기</button><button data-action="g43-hub">단계별 풀이 30개</button><button data-action="g43-review">다시 볼 단계별 풀이</button><button data-action="v42-campaigns">종합 문제 풀기</button><button data-action="v42-projects">나의 설명 작성하기</button></div><p class="smalltext muted">개념과 예제 풀이를 자신의 말로 정리하면 헷갈린 부분을 확인할 수 있습니다. 작성한 글은 자동 채점하지 않습니다.</p></section>'
 +'<h2 class="section">세 가지 주제 집중 탐구</h2><p>기회비용, 공공재, 무역을 사례와 계산으로 다시 살펴보세요.</p><div class="map-block">'+cityMap()+'<div class="map-buttons">'+CASES.map(c=>'<button data-action="case" data-id="'+c.id+'">'+esc(c.title)+'</button>').join('')+'</div></div>'
 +'<section class="card section"><h2>학습 기록 보관</h2><p>학습 기록은 현재 브라우저에 저장됩니다. 브라우저 데이터를 지우거나 다른 기기로 옮기기 전에는 백업 파일을 별도로 보관하세요.</p><div class="actions"><button data-action="settings">백업·복원 관리</button><button data-action="s431-import43">이전 4.3 기록 가져오기</button></div><details><summary>개정 안내와 기능 점검</summary><p>이번 판은 강의·문항·해설·화면 문구를 다듬은 문장 개정판입니다. 기존 학습 기록의 형식과 문항 식별자는 유지합니다.</p><button data-action="v42-report">개정 안내·점검 도구</button></details></section>';
};
releaseHTML42=function(){
 return '<div class="narrow"><span class="eyebrow">경제 설계자 4.3.1 · 문장 개정판</span><h1>개정 안내와 기능 점검</h1><section class="card"><h2>개정 범위</h2><p>72강의 본문과 예제, 정규 연습 195문항, 종합 문제 24단계, 단계별 풀이 30개, 집중 탐구의 12강·24활동, 실험실과 작성 활동의 안내를 다듬었습니다.</p><p>계산 수치와 정답 조건, 문항 식별자, 저장 형식은 기존 검증본을 기준으로 유지합니다. 개념의 출처와 각 학습용 모형의 가정은 참고 자료 및 문제의 조건에서 확인할 수 있습니다.</p><button data-action="s431-report">개정·사용 안내 TXT</button></section><section class="card section"><h2>현재 브라우저에서 기능 점검하기</h2><p>아래 검사는 학습 기록의 메모리 사본을 사용하며 검사 중 저장을 막습니다. 내부 계산과 복원 처리 등을 점검하지만, 실제 기기의 터치 조작·파일 보관·홈 화면 설치까지 확인하는 검사는 아닙니다.</p><div class="actions"><button class="primary" data-action="v42-audit">지금 검사 실행</button><button data-action="v42-export-test">이번 검사 결과 JSON</button></div><div id="audit42"></div></section><section class="card section"><h2>기록을 안전하게 보관하려면</h2><p>중요한 학습 기록과 작성한 글은 백업 파일로 따로 보관하세요. 복원 미리보기에서는 현재 기록을 바꾸지 않으며, 적용을 확인하면 백업의 기록으로 교체합니다. 두 기록을 합치는 기능은 아닙니다.</p><p class="smalltext muted">문항의 정답 기록, 강의의 읽음 표시, 자유 서술의 작성 기록은 서로 다릅니다. 자유 서술의 정확성을 자동으로 평가하거나 출간 적합성을 인증하지 않습니다.</p></section></div>';
};
report431=function(){
 return '경제 설계자 4.3.1 · 문장 개정판\n\n[개정 범위]\n강의 72개, 정규 연습 195문항, 종합 문제 24단계, 단계별 풀이 30개, 집중 탐구 12강·24활동의 문장을 다듬었습니다. 단원·실험실·작성 활동·화면 안내도 함께 정리했습니다. 새 문항을 추가한 판은 아닙니다.\n\n[개념과 계산]\n참고 자료의 분류 차이와 학습용 모형의 조건을 구분합니다. 비교값은 편익−명시적 비용이며 순편익과 다릅니다. 동아 교과서의 20인 모금 활동과 4인 토큰 게임은 서로 다른 조건입니다. 금융 수익률은 문제의 가정이며 미래 전망이나 투자 권유가 아닙니다.\n\n[학습 기록]\n기존 문항 식별자와 저장 형식을 유지합니다. 강의 읽음, 정답 기록, 자유 서술은 별도로 기록합니다. 자유 서술은 자동 채점하지 않습니다. 기록은 현재 브라우저에 저장되므로 외부 백업 파일도 보관해야 합니다.\n\n[백업과 복원]\n복원 미리보기는 현재 기록을 바꾸지 않습니다. 적용을 확인하면 백업 기록으로 교체하며 두 기록을 합치지 않습니다. 교체 직전 사본은 같은 브라우저의 최근 한 벌이므로 외부 파일 백업을 대신하지 못합니다. 지원 제작 버전은 4.2-full-course.1, 4.3-guided-review.1, 4.3.1-recovery.1입니다. 이름이 같더라도 다른 저장 형식의 파일은 호환되지 않을 수 있습니다.\n\n[검사 결과의 해석]\n실행한 자동 검사와 그 결과는 저장소의 검증 보고서에서 확인합니다. 화면의 내부 자가검사는 실제 기기의 터치·홈 화면 설치·파일 보관 검사를 대신하지 않습니다. 실제 기기 검증, 학습 시간 측정, 원교재의 모든 표와 그림에 대한 전수 검수와 구분해야 합니다.\n';
};
courseProgressReport41=report431;
